### ISSUE TITLE
use in browser?

### ISSUE THREAD

**Issue by jmcbee** [atom/highlights#10]
Hi, is it possible to use this in the browser?

**Comment by christophercliff** [comment]
Think it's feasible to swap out oniguruma for something browser-compatible?

**Comment by tenbits** [comment]
@christophercliff  It is not a trivial task, as oniguruma uses Ruby regular expressions, and there are a lot features which are not supported by JavaScript implementation of the regular expression. But I have started an attempt to add missing features - [Regex](https://github.com/tenbits/regex) I have also opened a request about making all this things browser-compatible - https://github.com/atom/first-mate/issues/65. Lets see what the maintainers think about this.

**Comment by bcoe** [comment]
I've created a pure-JavaScript version of oniguruma that _mostly_ works, would love help -- and would happily pull in features from @tenbits' `Regex`:

https://github.com/bcoe/onigurumajs

I have a port of highlights that runs without compiling:

https://www.npmjs.com/package/atom-highlightsjs

**Comment by tenbits** [comment]
Hey Benjamin, you are using the XRegexp library. I've seen it before, but unfortunately it won't be possible to extend it in that way, so that the oniguruma features are supported. That's why I've started the project from scratch. First of all the calculation of the `start` position of a captured group is only in the simplest cases possible with `indexOf`. Have you tried to run `first-mate` unit tests?

**Comment by xennygrimmato** [comment]
Is there any update on this? Can I generate HTML from the browser?
